#zastava BiH
#nisam nacionalista, ide neka osa, nesto...
print("         GET WASPED, BITCH!")
print("    .                         .")
print("    |.                       .|")
print("    | .                     . | ")
print("    |  .                   .  |")
print("    |   .                 .   |")
print("    |____.               .____|")
print("          ._____________.       ")
print("   \\______|__         __|_______/")
print("           | \\---------/ | ")
print("           \ /         \ /")
print("            / |x|   |x| \\")
print("            \ |x|   |x| /_______/\\")
print("       /\____\         /_____/\   \\")
print("      //\_____\___||__/_____/\ \   \\")
print("     //        0000000        \ \   \\")
print("    //         0000000         \ \   \\")
print("  _//           00000           \ \_  \_")
print("  _/             000             \_  ")
print("                  0")
